#!/bin/bash
#
# Version 2
#  - implement pull if repository already exist
#
# Version 1
#  - initial release
#
# cmgs - clone my github stars!
#
# REQUIREMENTS: wget, grep, cat, cut, git
#
# USAGE
#
#	$ chmod u+x cmgs
#	$ mkdir myGITHUBfavs
#	$ ./cmgs markuman myGITHUBfavs
#	...
#	$ ls myGITHUBfavs/
#	aeolianine  arasbm  dac922     devsnd  elecay    hoytech     kaosat-dev  lukasepple  silentbicycle  stetro    waalt    yexiaobo-seeedstudio
#	alabid      bartaz  dantswain  Dmytry  fguillot  irungentoo  kcuzner     priyadi     sn0opy         thliebig  xmarcux  yui
#


if (("$#" < 2)); then
	echo -e "Error: At least 2 arguments are needed. Your Github-Username and a destination dir.\n"
elif (("$#" > 2)); then
	echo -e "Error: Too much input arguments. Just 2 are needed. Github-Username and a destination dir.\n"
else

	# where am i?
	currentdir=$(pwd)
	# create temporary dir
	tmpdir=$(mktemp -d)

	# username + destination dir.
	githubuser=$1
	destdir=$2

	echo "Using tmpdir $tmpdir"
	wget -qP $tmpdir https://github.com/stars/$githubuser/

	grep "<h3>" $tmpdir/index.html > $tmpdir/stars.raw
	cat $tmpdir/stars.raw | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 > $tmpdir/stars.url

	filename=$tmpdir/stars.url
	while read -r line
	do
	    name=$line

	    if [ ! -d $destdir$name ]; then
   	    	echo -e "\n\n Start cloning $name \n"
	    	git clone https://github.com$name.git $destdir$name
	    else 
		echo -e "\n\n Pull $name \n"
		cd $destdir$name && git pull
		cd $currentdir
	    fi
	done < "$filename"

	rm -r $tmpdir
fi
