#!/bin/bash
#
# Version 9 - https://github.com/markuman/mygithub
#
# REQUIREMENTS: wget, grep, cut, git, sed
#
# USAGE
#
#	$ chmod u+x mygithub
#	$ ./mygithub markuman ~/GITHUB
#	...
#	$ ls ~GITHUB/
#	aeolianine  arasbm  dac922     devsnd  elecay    hoytech     kaosat-dev  lukasepple  silentbicycle  stetro    waalt    yexiaobo-seeedstudio
#	alabid      bartaz  dantswain  Dmytry  fguillot  irungentoo  kcuzner     priyadi     sn0opy         thliebig  xmarcux  yui
#
#	$ ./mygithub markuman /srv/http/viewgit/my-github-mirror/ justme
#

set -e

function single_git(){

	filename="$tmpdir"/gits.url
	while read -r line
	do
	    name=$line

	    # if github repository folder don't exist -> clone
	    if [ ! -d "$destdir$name" ]; then
   	    	echo -e "\n\n Start cloning $name \n"
	    	git clone --recursive https://github.com"$name".git "$destdir$name"
	    # if folder already exist -> pull
	    else 
		printf "\n\n Pull %s\n" "$name"
		cd "$destdir$name" && git pull
		cd "$currentdir"
	    fi
	done < "$filename"

}

#function parallel_git (){
#
# TODO: parallel clone/pull
#
#}



if (("$#" < 2)); then
	echo -e "Error: At least 2 arguments are needed. Your Github-Username and a destination dir.\n"
elif (("$#" > 3)); then
	echo -e "Error: Too much input arguments. Just 2 or 3 are needed. Github-Username and a destination dir.\n"
else
	# where am i?
	currentdir=$(pwd)
	# create temporary dir
	tmpdir=$(mktemp -d /tmp/mygithub.XXXXXX)

	# username + destination dir.
	githubuser=$1
	destdir=$2

	# destdir check
	if [ ! -d "$destdir" ]; then
		mkdir -p "$destdir"
	fi

	echo "Using tmpdir $tmpdir"
	# get the source...
	if (("$#" == 3)); then
		if [[ "$3" = "justme" ]]; then
			wget -qP "$tmpdir" https://github.com/"$githubuser"?tab=repositories
			sed -n "/<h3 class=\"repolist-name\">/,/h3>/"p "$tmpdir"/"$githubuser"\?tab\=repositories >> "$tmpdir"/gits.raw
			grep -o -E 'href="([^"#]+)"' "$tmpdir"/gits.raw | cut -d'"' -f2 > "$tmpdir"/gits.url
		else
			echo -e "\nError: Unknown third option!\n"
			rmdir "$tmpdir"
			exit 1
		fi
	else
		wget -qP "$tmpdir" https://github.com/stars/"$githubuser"/
		wget -qP "$tmpdir" https://github.com/"$githubuser"?tab=repositories
		grep "<h3>" "$tmpdir"/index.html > "$tmpdir"/gits.raw
		sed -n "/<h3 class=\"repolist-name\">/,/h3>/"p "$tmpdir"/"$githubuser"\?tab\=repositories >> "$tmpdir"/gits.raw
		grep -o -E 'href="([^"#]+)"' "$tmpdir"/gits.raw | cut -d'"' -f2 > "$tmpdir"/gits.url
	fi

	single_git "$@"
	
	# delete tmpdir
	rm -r "$tmpdir"
fi
