#!/bin/bash
#
# Version 8
# - MAC OS compatible mktemp -dt option
#
# Version 7
# - clone -recursive by default
#
# Verion 6
# - improve third option input.
#   it's set now to "justme".
#
# Version 5
# - support mirroring only repositories from given username
# e.g. $ ./mygithub markuman /mnt/GITHUB/ justme
# it's a weak implementation, because it doesn't matter what kind of string the third option is!
#
# Version 4
# - remove cat dependency
# - fix bug while extracting own repositories
# - verbose remove tmpdir
#
# Version 3
# - rename cmgs to mygithub
# - clone/pull stars and own github repositories
# - mkdir -p for destination dir
#
# Version 2
#  - implement pull if repository already exist
#
# Version 1
#  - initial release
#
#
# REQUIREMENTS: wget, grep, cut, git, sed
#
# USAGE
#
#	$ chmod u+x mygithub
#	$ ./mygithub markuman ~/GITHUB
#	...
#	$ ls myGITHUBfavs/
#	aeolianine  arasbm  dac922     devsnd  elecay    hoytech     kaosat-dev  lukasepple  silentbicycle  stetro    waalt    yexiaobo-seeedstudio
#	alabid      bartaz  dantswain  Dmytry  fguillot  irungentoo  kcuzner     priyadi     sn0opy         thliebig  xmarcux  yui
#
#	$ ./mygithub markuman /srv/http/viewgit/my-github-mirror/ justme
#

set -e

if (("$#" < 2)); then
	echo -e "Error: At least 2 arguments are needed. Your Github-Username and a destination dir.\n"
elif (("$#" > 3)); then
	echo -e "Error: Too much input arguments. Just 2 or 3 are needed. Github-Username and a destination dir.\n"
else
	# where am i?
	currentdir=$(pwd)
	# create temporary dir
	tmpdir=$(mktemp -dt)

	# username + destination dir.
	githubuser=$1
	destdir=$2

	# destdir check
	if [ ! -d $destdir ]; then
		mkdir -p $destdir
	fi

	echo "Using tmpdir $tmpdir"
	# get the source...
	if (("$#" == 3)); then
		if [[ "$3" = "justme" ]]; then
			wget -qP $tmpdir https://github.com/$githubuser?tab=repositories
			sed -n "/<h3 class=\"repolist-name\">/,/h3>/"p $tmpdir/$githubuser\?tab\=repositories >> $tmpdir/gits.raw
			grep -o -E 'href="([^"#]+)"' $tmpdir/gits.raw | cut -d'"' -f2 > $tmpdir/gits.url
		else
			echo -e "\nError: Unknown third option!\n"
			rmdir $tmpdir
			exit 1
		fi
	else
		wget -qP $tmpdir https://github.com/stars/$githubuser/
		wget -qP $tmpdir https://github.com/$githubuser?tab=repositories
		grep "<h3>" $tmpdir/index.html > $tmpdir/gits.raw
		sed -n "/<h3 class=\"repolist-name\">/,/h3>/"p $tmpdir/$githubuser\?tab\=repositories >> $tmpdir/gits.raw
		grep -o -E 'href="([^"#]+)"' $tmpdir/gits.raw | cut -d'"' -f2 > $tmpdir/gits.url
	fi

	filename=$tmpdir/gits.url
	while read -r line
	do
	    name=$line

	    # if github repository folder don't exist -> clone
	    if [ ! -d $destdir$name ]; then
   	    	echo -e "\n\n Start cloning $name \n"
	    	git clone --recursive https://github.com$name.git $destdir$name
	    # if folder already exist -> pull
	    else 
		echo -e "\n\n Pull $name \n"
		cd $destdir$name && git pull
		cd $currentdir
	    fi
	done < "$filename"

	# delete tmpdir
	rm -r $tmpdir
fi
